name: tasbeh
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.1
  percent_indicator: ^4.2.2
  text_scroll: ^0.1.0
  animated_splash_screen: ^1.3.0
  provider: ^6.0.4
  liquid_pull_to_refresh: ^3.0.1


  #android/app/src/debug/androidManiifefest/  <uses-permission android:name="android.permission.VIBRATE"/> /!
  flutter_vibrate: ^1.3.0

  

 
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"
  min_sdk_android: 21

  


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
 